name: Dependency Review
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2025-03-07T07%3A41%3A11.719000Z@time-machines-npm.sealsecurity.io/
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
